name: synadart
version: 0.4.4

description: >-
  A limited but fully documented neural network library created for educational
  purposes.

homepage: https://github.com/wordcollector/synadart
repository: https://github.com/wordcollector/synadart
issue_tracker: https://github.com/wordcollector/synadart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Logging
  sprint: ^1.0.4

dev_dependencies:
  words: ^0.1.1
